pipeline {
    agent any

    environment {
        NODE_ENV = 'development'
    }

    stages {
        stage('Hello') {
            steps {
                echo 'Hello from Jenkins Pipeline!'
                echo 'how are you fellas ?'
            }
        }
        stage('Install'){
            steps {
               dir('backend') {
                    echo 'Installing dependencies for backend...'
                    sh 'npm install'
                }
                dir('frontend') {
                    echo 'Installing dependencies for frontend...'
                    sh 'npm install'
                }
            }
        }
        stage('Run Frontend') {
            when {
                expression { env.NODE_ENV == 'development' }
            }
            steps {
                dir('frontend') {
                    echo 'Building frontend...'
                     sh 'nohup npm run dev &' // Run frontend in the background
                }
            }
        }
        stage('Run Backend') {
            when {
                expression { env.NODE_ENV == 'development' }
            }
            steps {
                dir('backend') {
                    echo 'Starting backend server...'
                    sh 'docker compose down'
                    sh 'docker compose up -d'
                }
            }
        }
    }
}