pipeline {
    agent any

    environment {

    }

    stages {
        stage('Hello') {
            steps {
                echo 'Hello from Jenkins Pipeline!'
                echo 'how are you fellas ?'
            }
        }
        stage('Install'){
            steps {
               dir('backend') {
                    echo 'Installing dependencies for backend...'
                    bat 'npm install'
                }
                dir('frontend') {
                    echo 'Installing dependencies for frontend...'
                    bat 'npm install'
                }
            }
        }
        stage('Run Frontend') {
            when {
                expression { env.NODE_ENV == 'development' }
            }
            steps {
                dir('frontend') {
                    echo 'Building frontend...'
                     bat 'start /B npm run dev' // Run frontend in the background
                }
            }
        }
        stage('Run Backend') {
            when {
                expression { env.NODE_ENV == 'development' }
            }
            steps {
                dir('backend') {
                    echo 'Starting backend server...'
                    echo 'Creating .env file for Docker Compose...'
            writeFile file: '.env', text: """
MONGODB_URI=${env.MONGODB_URI}
PORT=${env.PORT}
JWT_SECRET=${env.JWT_SECRET}
NODE_ENV=${env.NODE_ENV}
CLOUDINARY_CLOUD_NAME=${env.CLOUDINARY_CLOUD_NAME}
CLOUDINARY_API_KEY=${env.CLOUDINARY_API_KEY}
CLOUDINARY_API_SECRET=${env.CLOUDINARY_API_SECRET}
UPSTASH_REDIS_URL=${env.UPSTASH_REDIS_URL}
ADMIN_PASSWORD=${env.ADMIN_PASSWORD}
ARCJET_KEY=${env.ARCJET_KEY}
STEAM_API_KEY=${env.STEAM_API_KEY}
STEAM_API_SECRET=${env.STEAM_API_SECRET}
VITE_STREAM_API_KEY=${env.VITE_STREAM_API_KEY}
"""
            echo 'Starting backend server...'

                    bat 'docker compose up -d'
                }
            }
        }
    }
}